FROM --platform=linux/amd64 python:latest

# Set the working directory
WORKDIR /user/backend

EXPOSE 8000

RUN  pip install --upgrade pip

COPY ./requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

CMD uvicorn src.main:backend_app --reload --workers 4 --host 0.0.0.0 --port 8000